### ISSUE TITLE
Prepare high level roadmap

### ISSUE THREAD

**Issue by cadobre** [3angleTech/webFrame#1]
### Why
We need a high level roadmap that will present the major feature areas that webFrame needs to support. Also we should add some rough estimates, and based on this draft roadmap we will have a discussion in the team to see what is missing, what we can remove and how we can prioritize the tasks.

### What
- Prepare a high level drafts of the roadmap.
- Add estimates

**Comment by cadobre** [comment]
1. Bootstrap npm
2. 
3. ScriptUtils:
isNil
tryGet
coerceProperty
swapObjectKeys
getEnums
firstOrDefault
assign
convertObjectKeys
getStartOfDayWithoutTimezone

4. DataLayer - SerializableObjects.
5. Bootstrap application (WebFrame + WebModule)
6. WebFrameContext:
- current logged in User.
- access/refresh token.
- translation service.
- application configuration settings
- api : A property bag that has a list of all the supported services that communicate with the backend
- easy access to various features used extensively throughout each module: notifications, confirmations etc.

**Comment by mcristi** [comment]
- theming example
- angular mat style override example + best practices 
- index for readme/documentation + links between MD files
- refresh menu on events without page refresh (eg. if current user privileges changed)
