### ISSUE TITLE
Add support for deployUrl

### ISSUE THREAD

**Issue by SchnWalter** [3angleTech/webFrame#143]
## Why

Currently, the application works properly only on the domain or subdomain root. If it's moved to a subpath, various resources that contain URLs that start with slash (assets paths, `window.href` "forced-reloads") won't work

## What

* Update `IEnvironmentConfig.appBaseUrl` to use Angular CLI `--deployUrl` flag when it's properly implemented
  * https://github.com/angular/angular-cli/issues/17737
  * https://github.com/angular/angular-cli/issues/6666

**Comment by koekj** [comment]
If possible it would also be nice if the deploymentUrl can be made available in the application itself. As for instance I'm using configuration that relates to the deployment url as startng path. Another option would be to use a macro ${angular.deployUrl} in the generation of the code so that it can be replace in run time?

**Comment by SchnWalter** [comment]
I haven't checked, and it isn't immediately obvious from the standard, but since `<a href="#anchor">Anker</a>` produces an URL that contains the base, you should be able to use the URL class to retrieve the deployUrl, so a simple wrapper service will probably do the trick.

> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

Thanks for mentioning this.

**Comment by koekj** [comment]
I;m using two parameters the deploy url and the base-href which I then manipulate in the index.html
I'm using currently @{angular.deployUrl} as deployUrl and then run a script on runtime over .js,.html,.css and .json to replace this macro in the real url
`find dist/$APP_NAME \\( -type d -name .git -prune \\) -o -type f \\( -iname '*.css' -o -iname '*.html' -o -iname '*.js' -o -iname '*.json' \\) -print0 | xargs -0 sed -i \"s|@{angular\\.deployUrl}|$APP_DEPLOY_URL|g\" && node dist/$APP_NAME/server/$APP_LANG/main.js --appName=$APP_NAME --baseUrl=$APP_BASE_URL --configFile=$APP_CONFIG_FILE --deployUrl=$APP_DEPLOY_URL --lang=$APP_LANG"
`

**Comment by koekj** [comment]
the deploy url is even injected in the server side code and then transferred to the angular app by a provider so that I can use it at runtime to get the configuration from the right sub url

**Comment by SchnWalter** [comment]
I would go with some different translation system that allows you to change the language at runtime, [@ngx-translate/core](https://www.npmjs.com/package/@ngx-translate/core) is a good one, but you should probably replace the default pipe, since it does a lot of work during Change Detection. And I think that SSR should work out of the box, just make sure to add the language codes in the URL.

**Comment by SchnWalter** [comment]
Closing, deployUrl is now deprecated: https://github.com/angular/angular-cli/commit/e95ecb8ab0382eb803741619c446d6cc7b215ba0
