### ISSUE TITLE
Fix linting errors

### ISSUE THREAD

**Issue by cadobre** [3angleTech/webFrame#63]
### Why
After adding more linting rules, we are seeing linting erros.
Related issue: https://github.com/3angleTech/webFrame/issues/19

### What

Fix linting errors. Create new branch and merge in branch 19-tslint

**Comment by cadobre** [comment]
Forgot to mention in the story that below rules should be enabled:
"no-submodule-imports": true,
"function-name": true,
"no-duplicate-string": true,

**Comment by SchnWalter** [comment]
Resolved in  #65
